// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project_NO_BG

#include "ui.h"

lv_obj_t * ui_DriveStatusScreen = NULL;
lv_obj_t * ui_StatusLabelStatus = NULL;
lv_obj_t * ui_HomeButtonStatus = NULL;
lv_obj_t * ui_HomeButtonStatusLabel = NULL;
lv_obj_t * ui_ConsoleReadStatus = NULL;
lv_obj_t * ui_DriveNameStatus = NULL;
lv_obj_t * ui_EnaNetworkButtonStatus = NULL;
lv_obj_t * ui_EnaNetworkButtonStatusLabel = NULL;
lv_obj_t * ui_FactoryResetButtonStatus = NULL;
lv_obj_t * ui_FactoryResetButtonStatusLabel = NULL;
lv_obj_t * ui_StatusReadout = NULL;
lv_obj_t * ui_GV6k_Logo_Home2 = NULL;
lv_obj_t * ui_GEMINI_LABEL_HOME2 = NULL;
lv_obj_t * ui_SpinnerStatus = NULL;
// event funtions

// build funtions

void ui_DriveStatusScreen_screen_init(void)
{
    ui_DriveStatusScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_DriveStatusScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_DriveStatusScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_DriveStatusScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_StatusLabelStatus = lv_label_create(ui_DriveStatusScreen);
    lv_obj_set_width(ui_StatusLabelStatus, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_StatusLabelStatus, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_StatusLabelStatus, 555);
    lv_obj_set_y(ui_StatusLabelStatus, -205);
    lv_obj_set_align(ui_StatusLabelStatus, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_StatusLabelStatus, "Not Connected");
    lv_obj_set_style_text_color(ui_StatusLabelStatus, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_StatusLabelStatus, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_StatusLabelStatus, &ui_font_OSF_REG_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HomeButtonStatus = lv_btn_create(ui_DriveStatusScreen);
    lv_obj_set_width(ui_HomeButtonStatus, 200);
    lv_obj_set_height(ui_HomeButtonStatus, 66);
    lv_obj_set_x(ui_HomeButtonStatus, 250);
    lv_obj_set_y(ui_HomeButtonStatus, -145);
    lv_obj_set_align(ui_HomeButtonStatus, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_HomeButtonStatus, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_HomeButtonStatus, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_HomeButtonStatus, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_HomeButtonStatus, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HomeButtonStatus, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_HomeButtonStatus, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_HomeButtonStatus, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_HomeButtonStatus, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_HomeButtonStatus, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HomeButtonStatusLabel = lv_label_create(ui_HomeButtonStatus);
    lv_obj_set_width(ui_HomeButtonStatusLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HomeButtonStatusLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_HomeButtonStatusLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HomeButtonStatusLabel, "Home");
    lv_obj_set_style_text_color(ui_HomeButtonStatusLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_HomeButtonStatusLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HomeButtonStatusLabel, &ui_font_OSF_REG_42, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ConsoleReadStatus = lv_textarea_create(ui_DriveStatusScreen);
    lv_obj_set_width(ui_ConsoleReadStatus, 800);
    lv_obj_set_height(ui_ConsoleReadStatus, 167);
    lv_obj_set_align(ui_ConsoleReadStatus, LV_ALIGN_BOTTOM_MID);
    lv_textarea_set_placeholder_text(ui_ConsoleReadStatus, "SAMPLE CONSOLE READOUT");
    lv_obj_clear_flag(ui_ConsoleReadStatus,
                      LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_obj_set_scroll_snap_y(ui_ConsoleReadStatus, LV_SCROLL_SNAP_END);
    lv_obj_set_style_text_color(ui_ConsoleReadStatus, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ConsoleReadStatus, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ConsoleReadStatus, &ui_font_OSF_REG_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_ConsoleReadStatus, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ConsoleReadStatus, lv_color_hex(0x131313), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ConsoleReadStatus, 125, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ConsoleReadStatus, lv_color_hex(0xD5D6D8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ConsoleReadStatus, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ConsoleReadStatus, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_ConsoleReadStatus, LV_BORDER_SIDE_TOP, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DriveNameStatus = lv_label_create(ui_DriveStatusScreen);
    lv_obj_set_width(ui_DriveNameStatus, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DriveNameStatus, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DriveNameStatus, 230);
    lv_obj_set_y(ui_DriveNameStatus, 25);
    lv_label_set_text(ui_DriveNameStatus, "U12");
    lv_obj_set_style_text_color(ui_DriveNameStatus, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DriveNameStatus, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_DriveNameStatus, &ui_font_OSF_72, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_EnaNetworkButtonStatus = lv_btn_create(ui_DriveStatusScreen);
    lv_obj_set_width(ui_EnaNetworkButtonStatus, 220);
    lv_obj_set_height(ui_EnaNetworkButtonStatus, 100);
    lv_obj_set_x(ui_EnaNetworkButtonStatus, -275);
    lv_obj_set_y(ui_EnaNetworkButtonStatus, -20);
    lv_obj_set_align(ui_EnaNetworkButtonStatus, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_EnaNetworkButtonStatus, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_EnaNetworkButtonStatus, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_EnaNetworkButtonStatus, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_EnaNetworkButtonStatus, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_EnaNetworkButtonStatus, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_EnaNetworkButtonStatus, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_EnaNetworkButtonStatus, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_EnaNetworkButtonStatus, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_EnaNetworkButtonStatus, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_EnaNetworkButtonStatusLabel = lv_label_create(ui_EnaNetworkButtonStatus);
    lv_obj_set_width(ui_EnaNetworkButtonStatusLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_EnaNetworkButtonStatusLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_EnaNetworkButtonStatusLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_EnaNetworkButtonStatusLabel, "Enable\nNetwork");
    lv_obj_set_style_text_color(ui_EnaNetworkButtonStatusLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_EnaNetworkButtonStatusLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_EnaNetworkButtonStatusLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_EnaNetworkButtonStatusLabel, &ui_font_OSF_REG_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_FactoryResetButtonStatus = lv_btn_create(ui_DriveStatusScreen);
    lv_obj_set_width(ui_FactoryResetButtonStatus, 220);
    lv_obj_set_height(ui_FactoryResetButtonStatus, 100);
    lv_obj_set_x(ui_FactoryResetButtonStatus, 0);
    lv_obj_set_y(ui_FactoryResetButtonStatus, -20);
    lv_obj_set_align(ui_FactoryResetButtonStatus, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_FactoryResetButtonStatus, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_FactoryResetButtonStatus, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_FactoryResetButtonStatus, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_FactoryResetButtonStatus, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_FactoryResetButtonStatus, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_FactoryResetButtonStatus, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_FactoryResetButtonStatus, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_FactoryResetButtonStatus, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_FactoryResetButtonStatus, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_FactoryResetButtonStatusLabel = lv_label_create(ui_FactoryResetButtonStatus);
    lv_obj_set_width(ui_FactoryResetButtonStatusLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_FactoryResetButtonStatusLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_FactoryResetButtonStatusLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_FactoryResetButtonStatusLabel, "Factory\nReset");
    lv_obj_set_style_text_color(ui_FactoryResetButtonStatusLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_FactoryResetButtonStatusLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_FactoryResetButtonStatusLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_FactoryResetButtonStatusLabel, &ui_font_OSF_REG_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_StatusReadout = lv_textarea_create(ui_DriveStatusScreen);
    lv_obj_set_width(ui_StatusReadout, 244);
    lv_obj_set_height(ui_StatusReadout, 140);
    lv_obj_set_x(ui_StatusReadout, 263);
    lv_obj_set_y(ui_StatusReadout, -18);
    lv_obj_set_align(ui_StatusReadout, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_StatusReadout, "COMMAND DIR: 0\nSGINTE\nLJRAT\nLDAMP");
    lv_textarea_set_placeholder_text(ui_StatusReadout, "Placeholder...");
    lv_obj_add_flag(ui_StatusReadout, LV_OBJ_FLAG_SCROLL_WITH_ARROW);     /// Flags
    lv_obj_clear_flag(ui_StatusReadout, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE);      /// Flags
    lv_obj_set_style_text_color(ui_StatusReadout, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_StatusReadout, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_StatusReadout, &ui_font_OSF_REG_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_StatusReadout, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_StatusReadout, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_StatusReadout, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_GV6k_Logo_Home2 = lv_img_create(ui_DriveStatusScreen);
    lv_img_set_src(ui_GV6k_Logo_Home2, &ui_img_gv6k_png);
    lv_obj_set_width(ui_GV6k_Logo_Home2, LV_SIZE_CONTENT);   /// 529
    lv_obj_set_height(ui_GV6k_Logo_Home2, LV_SIZE_CONTENT);    /// 501
    lv_obj_set_x(ui_GV6k_Logo_Home2, -353);
    lv_obj_set_y(ui_GV6k_Logo_Home2, -185);
    lv_obj_set_align(ui_GV6k_Logo_Home2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_GV6k_Logo_Home2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_GV6k_Logo_Home2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_GV6k_Logo_Home2, 350);

    ui_GEMINI_LABEL_HOME2 = lv_label_create(ui_DriveStatusScreen);
    lv_obj_set_width(ui_GEMINI_LABEL_HOME2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_GEMINI_LABEL_HOME2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_GEMINI_LABEL_HOME2, 86);
    lv_obj_set_y(ui_GEMINI_LABEL_HOME2, 39);
    lv_label_set_text(ui_GEMINI_LABEL_HOME2, "EMINI");
    lv_obj_set_style_text_color(ui_GEMINI_LABEL_HOME2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_GEMINI_LABEL_HOME2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_GEMINI_LABEL_HOME2, &ui_font_OSF_REG_42, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SpinnerStatus = lv_spinner_create(ui_DriveStatusScreen, 1000, 90);
    lv_obj_set_width(ui_SpinnerStatus, 102);
    lv_obj_set_height(ui_SpinnerStatus, 111);
    lv_obj_set_x(ui_SpinnerStatus, 45);
    lv_obj_set_y(ui_SpinnerStatus, -146);
    lv_obj_set_align(ui_SpinnerStatus, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_SpinnerStatus, LV_OBJ_FLAG_CLICKABLE);      /// Flags

}

void ui_DriveStatusScreen_screen_destroy(void)
{
    if(ui_DriveStatusScreen) lv_obj_del(ui_DriveStatusScreen);

    // NULL screen variables
    ui_DriveStatusScreen = NULL;
    ui_StatusLabelStatus = NULL;
    ui_HomeButtonStatus = NULL;
    ui_HomeButtonStatusLabel = NULL;
    ui_ConsoleReadStatus = NULL;
    ui_DriveNameStatus = NULL;
    ui_EnaNetworkButtonStatus = NULL;
    ui_EnaNetworkButtonStatusLabel = NULL;
    ui_FactoryResetButtonStatus = NULL;
    ui_FactoryResetButtonStatusLabel = NULL;
    ui_StatusReadout = NULL;
    ui_GV6k_Logo_Home2 = NULL;
    ui_GEMINI_LABEL_HOME2 = NULL;
    ui_SpinnerStatus = NULL;

}
