// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project_NO_BG

#ifndef UI_DRIVESTATUSSCREEN_H
#define UI_DRIVESTATUSSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_DriveStatusScreen
extern void ui_DriveStatusScreen_screen_init(void);
extern void ui_DriveStatusScreen_screen_destroy(void);
extern lv_obj_t * ui_DriveStatusScreen;
extern lv_obj_t * ui_StatusLabelStatus;
extern lv_obj_t * ui_HomeButtonStatus;
extern lv_obj_t * ui_HomeButtonStatusLabel;
extern lv_obj_t * ui_ConsoleReadStatus;
extern lv_obj_t * ui_DriveNameStatus;
extern lv_obj_t * ui_EnaNetworkButtonStatus;
extern lv_obj_t * ui_EnaNetworkButtonStatusLabel;
extern lv_obj_t * ui_FactoryResetButtonStatus;
extern lv_obj_t * ui_FactoryResetButtonStatusLabel;
extern lv_obj_t * ui_StatusReadout;
extern lv_obj_t * ui_GV6k_Logo_Home2;
extern lv_obj_t * ui_GEMINI_LABEL_HOME2;
extern lv_obj_t * ui_SpinnerStatus;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

