// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project_NO_BG

#include "ui.h"

lv_obj_t * ui_HomeScreen = NULL;
lv_obj_t * ui_StatusLabelHome = NULL;
lv_obj_t * ui_DriveName = NULL;
lv_obj_t * ui_IPConfigButtonHome = NULL;
lv_obj_t * ui_IPConfigButtonHomeLabel = NULL;
lv_obj_t * ui_IPConfigButtonTitle = NULL;
lv_obj_t * ui_MotorConfigButtonHome = NULL;
lv_obj_t * ui_MotorConfigButtonHomeLabel = NULL;
lv_obj_t * ui_MotorConfigButtonTitle = NULL;
lv_obj_t * ui_DriveStatusButtonHome = NULL;
lv_obj_t * ui_DriveStatusButtonHomeLabel = NULL;
lv_obj_t * ui_DriveStatusButtonTitle = NULL;
lv_obj_t * ui_GV6k_Logo_Home = NULL;
lv_obj_t * ui_GEMINI_LABEL_HOME = NULL;
lv_obj_t * ui_OSF_Logo_Home = NULL;
lv_obj_t * ui_OSF_LABEL = NULL;
lv_obj_t * ui_AUTOMATION_LABEL = NULL;
// event funtions

// build funtions

void ui_HomeScreen_screen_init(void)
{
    ui_HomeScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_HomeScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_HomeScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HomeScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_StatusLabelHome = lv_label_create(ui_HomeScreen);
    lv_obj_set_width(ui_StatusLabelHome, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_StatusLabelHome, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_StatusLabelHome, 555);
    lv_obj_set_y(ui_StatusLabelHome, -205);
    lv_obj_set_align(ui_StatusLabelHome, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_StatusLabelHome, "NOT CONNECTED");
    lv_obj_set_style_text_color(ui_StatusLabelHome, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_StatusLabelHome, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_StatusLabelHome, &ui_font_OSF_REG_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DriveName = lv_label_create(ui_HomeScreen);
    lv_obj_set_width(ui_DriveName, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DriveName, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DriveName, 230);
    lv_obj_set_y(ui_DriveName, 25);
    lv_label_set_text(ui_DriveName, "U12");
    lv_obj_set_style_text_color(ui_DriveName, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DriveName, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_DriveName, &ui_font_OSF_72, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_IPConfigButtonHome = lv_btn_create(ui_HomeScreen);
    lv_obj_set_width(ui_IPConfigButtonHome, 359);
    lv_obj_set_height(ui_IPConfigButtonHome, 89);
    lv_obj_set_x(ui_IPConfigButtonHome, 187);
    lv_obj_set_y(ui_IPConfigButtonHome, -41);
    lv_obj_set_align(ui_IPConfigButtonHome, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_IPConfigButtonHome, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_IPConfigButtonHome, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_IPConfigButtonHome, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_IPConfigButtonHome, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_IPConfigButtonHome, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_IPConfigButtonHome, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_IPConfigButtonHome, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_IPConfigButtonHome, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_IPConfigButtonHome, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_IPConfigButtonHome, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_IPConfigButtonHome, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_IPConfigButtonHome, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_IPConfigButtonHomeLabel = lv_label_create(ui_IPConfigButtonHome);
    lv_obj_set_width(ui_IPConfigButtonHomeLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_IPConfigButtonHomeLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_IPConfigButtonHomeLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_IPConfigButtonHomeLabel, "192.168.10.166");
    lv_obj_set_style_text_color(ui_IPConfigButtonHomeLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_IPConfigButtonHomeLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_IPConfigButtonHomeLabel, &ui_font_OSF_REG_42, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_IPConfigButtonTitle = lv_label_create(ui_HomeScreen);
    lv_obj_set_width(ui_IPConfigButtonTitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_IPConfigButtonTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_IPConfigButtonTitle, 187);
    lv_obj_set_y(ui_IPConfigButtonTitle, -83);
    lv_obj_set_align(ui_IPConfigButtonTitle, LV_ALIGN_CENTER);
    lv_label_set_text(ui_IPConfigButtonTitle, "IP CONFIG");
    lv_obj_set_style_text_color(ui_IPConfigButtonTitle, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_IPConfigButtonTitle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_IPConfigButtonTitle, &ui_font_OSF_REG_22, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_IPConfigButtonTitle, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_IPConfigButtonTitle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_IPConfigButtonTitle, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_IPConfigButtonTitle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_IPConfigButtonTitle, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MotorConfigButtonHome = lv_btn_create(ui_HomeScreen);
    lv_obj_set_width(ui_MotorConfigButtonHome, 342);
    lv_obj_set_height(ui_MotorConfigButtonHome, 91);
    lv_obj_set_x(ui_MotorConfigButtonHome, -196);
    lv_obj_set_y(ui_MotorConfigButtonHome, -42);
    lv_obj_set_align(ui_MotorConfigButtonHome, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_MotorConfigButtonHome, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_MotorConfigButtonHome, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_MotorConfigButtonHome, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_MotorConfigButtonHome, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MotorConfigButtonHome, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_MotorConfigButtonHome, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_MotorConfigButtonHome, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_MotorConfigButtonHome, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_MotorConfigButtonHome, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_MotorConfigButtonHome, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_MotorConfigButtonHome, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_MotorConfigButtonHome, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MotorConfigButtonHomeLabel = lv_label_create(ui_MotorConfigButtonHome);
    lv_obj_set_width(ui_MotorConfigButtonHomeLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MotorConfigButtonHomeLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_MotorConfigButtonHomeLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MotorConfigButtonHomeLabel, "MPP 115 3C1E");
    lv_obj_set_style_text_color(ui_MotorConfigButtonHomeLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MotorConfigButtonHomeLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_MotorConfigButtonHomeLabel, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MotorConfigButtonHomeLabel, &ui_font_OSF_REG_42, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MotorConfigButtonTitle = lv_label_create(ui_HomeScreen);
    lv_obj_set_width(ui_MotorConfigButtonTitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MotorConfigButtonTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MotorConfigButtonTitle, -196);
    lv_obj_set_y(ui_MotorConfigButtonTitle, -83);
    lv_obj_set_align(ui_MotorConfigButtonTitle, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MotorConfigButtonTitle, "MOTOR CONFIG");
    lv_obj_set_style_text_color(ui_MotorConfigButtonTitle, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MotorConfigButtonTitle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MotorConfigButtonTitle, &ui_font_OSF_REG_22, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_MotorConfigButtonTitle, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MotorConfigButtonTitle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_MotorConfigButtonTitle, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_MotorConfigButtonTitle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_MotorConfigButtonTitle, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DriveStatusButtonHome = lv_btn_create(ui_HomeScreen);
    lv_obj_set_width(ui_DriveStatusButtonHome, 359);
    lv_obj_set_height(ui_DriveStatusButtonHome, 89);
    lv_obj_set_x(ui_DriveStatusButtonHome, 188);
    lv_obj_set_y(ui_DriveStatusButtonHome, 85);
    lv_obj_set_align(ui_DriveStatusButtonHome, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_DriveStatusButtonHome, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_DriveStatusButtonHome, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_DriveStatusButtonHome, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_DriveStatusButtonHome, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_DriveStatusButtonHome, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_DriveStatusButtonHome, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_DriveStatusButtonHome, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_DriveStatusButtonHome, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_DriveStatusButtonHome, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_DriveStatusButtonHome, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_DriveStatusButtonHome, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_DriveStatusButtonHome, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DriveStatusButtonHomeLabel = lv_label_create(ui_DriveStatusButtonHome);
    lv_obj_set_width(ui_DriveStatusButtonHomeLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DriveStatusButtonHomeLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_DriveStatusButtonHomeLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DriveStatusButtonHomeLabel, "Drive Status");
    lv_obj_set_style_text_color(ui_DriveStatusButtonHomeLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DriveStatusButtonHomeLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_DriveStatusButtonHomeLabel, &ui_font_OSF_REG_42, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DriveStatusButtonTitle = lv_label_create(ui_HomeScreen);
    lv_obj_set_width(ui_DriveStatusButtonTitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DriveStatusButtonTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DriveStatusButtonTitle, 187);
    lv_obj_set_y(ui_DriveStatusButtonTitle, 130);
    lv_obj_set_align(ui_DriveStatusButtonTitle, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DriveStatusButtonTitle, "VIEW");
    lv_obj_set_style_text_color(ui_DriveStatusButtonTitle, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DriveStatusButtonTitle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_DriveStatusButtonTitle, &ui_font_OSF_REG_22, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_DriveStatusButtonTitle, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_DriveStatusButtonTitle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_DriveStatusButtonTitle, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_DriveStatusButtonTitle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_DriveStatusButtonTitle, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_GV6k_Logo_Home = lv_img_create(ui_HomeScreen);
    lv_img_set_src(ui_GV6k_Logo_Home, &ui_img_gv6k_png);
    lv_obj_set_width(ui_GV6k_Logo_Home, LV_SIZE_CONTENT);   /// 529
    lv_obj_set_height(ui_GV6k_Logo_Home, LV_SIZE_CONTENT);    /// 501
    lv_obj_set_x(ui_GV6k_Logo_Home, -353);
    lv_obj_set_y(ui_GV6k_Logo_Home, -185);
    lv_obj_set_align(ui_GV6k_Logo_Home, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_GV6k_Logo_Home, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_GV6k_Logo_Home, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_GV6k_Logo_Home, 350);

    ui_GEMINI_LABEL_HOME = lv_label_create(ui_HomeScreen);
    lv_obj_set_width(ui_GEMINI_LABEL_HOME, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_GEMINI_LABEL_HOME, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_GEMINI_LABEL_HOME, 86);
    lv_obj_set_y(ui_GEMINI_LABEL_HOME, 39);
    lv_label_set_text(ui_GEMINI_LABEL_HOME, "EMINI");
    lv_obj_set_style_text_color(ui_GEMINI_LABEL_HOME, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_GEMINI_LABEL_HOME, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_GEMINI_LABEL_HOME, &ui_font_OSF_REG_42, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_OSF_Logo_Home = lv_img_create(ui_HomeScreen);
    lv_img_set_src(ui_OSF_Logo_Home, &ui_img_1999303404);
    lv_obj_set_width(ui_OSF_Logo_Home, LV_SIZE_CONTENT);   /// 572
    lv_obj_set_height(ui_OSF_Logo_Home, LV_SIZE_CONTENT);    /// 711
    lv_obj_set_x(ui_OSF_Logo_Home, -340);
    lv_obj_set_y(ui_OSF_Logo_Home, 138);
    lv_obj_set_align(ui_OSF_Logo_Home, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_OSF_Logo_Home, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_OSF_Logo_Home, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_OSF_Logo_Home, 150);

    ui_OSF_LABEL = lv_label_create(ui_HomeScreen);
    lv_obj_set_width(ui_OSF_LABEL, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_OSF_LABEL, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_OSF_LABEL, 114);
    lv_obj_set_y(ui_OSF_LABEL, -44);
    lv_obj_set_align(ui_OSF_LABEL, LV_ALIGN_BOTTOM_LEFT);
    lv_label_set_text(ui_OSF_LABEL, "Oregon Shakespeare Festival");
    lv_obj_set_style_text_color(ui_OSF_LABEL, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_OSF_LABEL, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_OSF_LABEL, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_OSF_LABEL, &ui_font_OSF24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AUTOMATION_LABEL = lv_label_create(ui_HomeScreen);
    lv_obj_set_width(ui_AUTOMATION_LABEL, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AUTOMATION_LABEL, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AUTOMATION_LABEL, 133);
    lv_obj_set_y(ui_AUTOMATION_LABEL, -64);
    lv_obj_set_align(ui_AUTOMATION_LABEL, LV_ALIGN_BOTTOM_LEFT);
    lv_label_set_text(ui_AUTOMATION_LABEL, "Automation");
    lv_obj_set_style_text_color(ui_AUTOMATION_LABEL, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_AUTOMATION_LABEL, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_AUTOMATION_LABEL, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_AUTOMATION_LABEL, &ui_font_OSF42, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_HomeScreen_screen_destroy(void)
{
    if(ui_HomeScreen) lv_obj_del(ui_HomeScreen);

    // NULL screen variables
    ui_HomeScreen = NULL;
    ui_StatusLabelHome = NULL;
    ui_DriveName = NULL;
    ui_IPConfigButtonHome = NULL;
    ui_IPConfigButtonHomeLabel = NULL;
    ui_IPConfigButtonTitle = NULL;
    ui_MotorConfigButtonHome = NULL;
    ui_MotorConfigButtonHomeLabel = NULL;
    ui_MotorConfigButtonTitle = NULL;
    ui_DriveStatusButtonHome = NULL;
    ui_DriveStatusButtonHomeLabel = NULL;
    ui_DriveStatusButtonTitle = NULL;
    ui_GV6k_Logo_Home = NULL;
    ui_GEMINI_LABEL_HOME = NULL;
    ui_OSF_Logo_Home = NULL;
    ui_OSF_LABEL = NULL;
    ui_AUTOMATION_LABEL = NULL;

}
