// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project_NO_BG

#ifndef UI_IPCONFIGSCREEN_H
#define UI_IPCONFIGSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_IPConfigScreen
extern void ui_IPConfigScreen_screen_init(void);
extern void ui_IPConfigScreen_screen_destroy(void);
extern lv_obj_t * ui_IPConfigScreen;
extern lv_obj_t * ui_DriveNameIPConfig;
extern lv_obj_t * ui_StatusLabelIPConfig;
extern lv_obj_t * ui_HomeButtonIPConfig;
extern lv_obj_t * ui_HomeButtonIPConfigLabel;
extern lv_obj_t * ui_ConsoleReadIPConfig;
extern lv_obj_t * ui_SpinnerIPConfig;
extern lv_obj_t * ui_SendButtonIPConfig;
extern lv_obj_t * ui_SendButtonIPConfigLabel;
extern lv_obj_t * ui_IPDigit1;
extern lv_obj_t * ui_IPDisplay;
extern lv_obj_t * ui_IPConfigPrevFieldButton;
extern lv_obj_t * ui_IPConfigPrevFieldButtonLabel;
extern lv_obj_t * ui_IPConfigNextFieldButton;
extern lv_obj_t * ui_IPConfigNextFieldButtonLabel;
extern lv_obj_t * ui_IPDigit2;
extern lv_obj_t * ui_IPDigit3;
extern lv_obj_t * ui_GV6k_Logo_Home3;
extern lv_obj_t * ui_GEMINI_LABEL_HOME3;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

