// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project_NO_BG

#include "ui.h"

lv_obj_t * ui_IPConfigScreen = NULL;
lv_obj_t * ui_DriveNameIPConfig = NULL;
lv_obj_t * ui_StatusLabelIPConfig = NULL;
lv_obj_t * ui_HomeButtonIPConfig = NULL;
lv_obj_t * ui_HomeButtonIPConfigLabel = NULL;
lv_obj_t * ui_ConsoleReadIPConfig = NULL;
lv_obj_t * ui_SpinnerIPConfig = NULL;
lv_obj_t * ui_SendButtonIPConfig = NULL;
lv_obj_t * ui_SendButtonIPConfigLabel = NULL;
lv_obj_t * ui_IPDigit1 = NULL;
lv_obj_t * ui_IPDisplay = NULL;
lv_obj_t * ui_IPConfigPrevFieldButton = NULL;
lv_obj_t * ui_IPConfigPrevFieldButtonLabel = NULL;
lv_obj_t * ui_IPConfigNextFieldButton = NULL;
lv_obj_t * ui_IPConfigNextFieldButtonLabel = NULL;
lv_obj_t * ui_IPDigit2 = NULL;
lv_obj_t * ui_IPDigit3 = NULL;
lv_obj_t * ui_GV6k_Logo_Home3 = NULL;
lv_obj_t * ui_GEMINI_LABEL_HOME3 = NULL;
// event funtions

// build funtions

void ui_IPConfigScreen_screen_init(void)
{
    ui_IPConfigScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_IPConfigScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_IPConfigScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_IPConfigScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DriveNameIPConfig = lv_label_create(ui_IPConfigScreen);
    lv_obj_set_width(ui_DriveNameIPConfig, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DriveNameIPConfig, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DriveNameIPConfig, 230);
    lv_obj_set_y(ui_DriveNameIPConfig, 25);
    lv_label_set_text(ui_DriveNameIPConfig, "U12");
    lv_obj_set_style_text_color(ui_DriveNameIPConfig, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DriveNameIPConfig, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_DriveNameIPConfig, &ui_font_OSF_72, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_StatusLabelIPConfig = lv_label_create(ui_IPConfigScreen);
    lv_obj_set_width(ui_StatusLabelIPConfig, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_StatusLabelIPConfig, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_StatusLabelIPConfig, 555);
    lv_obj_set_y(ui_StatusLabelIPConfig, -205);
    lv_obj_set_align(ui_StatusLabelIPConfig, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_StatusLabelIPConfig, "Not Connected");
    lv_obj_set_style_text_color(ui_StatusLabelIPConfig, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_StatusLabelIPConfig, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_StatusLabelIPConfig, &ui_font_OSF_REG_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HomeButtonIPConfig = lv_btn_create(ui_IPConfigScreen);
    lv_obj_set_width(ui_HomeButtonIPConfig, 200);
    lv_obj_set_height(ui_HomeButtonIPConfig, 66);
    lv_obj_set_x(ui_HomeButtonIPConfig, 250);
    lv_obj_set_y(ui_HomeButtonIPConfig, -145);
    lv_obj_set_align(ui_HomeButtonIPConfig, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_HomeButtonIPConfig, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_HomeButtonIPConfig, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_HomeButtonIPConfig, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_HomeButtonIPConfig, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HomeButtonIPConfig, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_HomeButtonIPConfig, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_HomeButtonIPConfig, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_HomeButtonIPConfig, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_HomeButtonIPConfig, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HomeButtonIPConfigLabel = lv_label_create(ui_HomeButtonIPConfig);
    lv_obj_set_width(ui_HomeButtonIPConfigLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HomeButtonIPConfigLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_HomeButtonIPConfigLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HomeButtonIPConfigLabel, "Home");
    lv_obj_set_style_text_color(ui_HomeButtonIPConfigLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_HomeButtonIPConfigLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HomeButtonIPConfigLabel, &ui_font_OSF_REG_42, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ConsoleReadIPConfig = lv_textarea_create(ui_IPConfigScreen);
    lv_obj_set_width(ui_ConsoleReadIPConfig, 800);
    lv_obj_set_height(ui_ConsoleReadIPConfig, 167);
    lv_obj_set_align(ui_ConsoleReadIPConfig, LV_ALIGN_BOTTOM_MID);
    lv_textarea_set_placeholder_text(ui_ConsoleReadIPConfig, "SAMPLE CONSOLE READOUT");
    lv_obj_clear_flag(ui_ConsoleReadIPConfig,
                      LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_obj_set_style_text_color(ui_ConsoleReadIPConfig, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ConsoleReadIPConfig, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ConsoleReadIPConfig, &ui_font_OSF_REG_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_ConsoleReadIPConfig, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ConsoleReadIPConfig, lv_color_hex(0x131313), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ConsoleReadIPConfig, 125, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ConsoleReadIPConfig, lv_color_hex(0xD5D6D8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ConsoleReadIPConfig, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ConsoleReadIPConfig, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_ConsoleReadIPConfig, LV_BORDER_SIDE_TOP, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SpinnerIPConfig = lv_spinner_create(ui_IPConfigScreen, 1000, 90);
    lv_obj_set_width(ui_SpinnerIPConfig, 105);
    lv_obj_set_height(ui_SpinnerIPConfig, 105);
    lv_obj_set_x(ui_SpinnerIPConfig, 76);
    lv_obj_set_y(ui_SpinnerIPConfig, -170);
    lv_obj_set_align(ui_SpinnerIPConfig, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SpinnerIPConfig, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_SpinnerIPConfig, LV_OBJ_FLAG_CLICKABLE);      /// Flags

    ui_SendButtonIPConfig = lv_btn_create(ui_IPConfigScreen);
    lv_obj_set_width(ui_SendButtonIPConfig, 189);
    lv_obj_set_height(ui_SendButtonIPConfig, 75);
    lv_obj_set_x(ui_SendButtonIPConfig, 272);
    lv_obj_set_y(ui_SendButtonIPConfig, -20);
    lv_obj_set_align(ui_SendButtonIPConfig, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SendButtonIPConfig, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_SendButtonIPConfig, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_SendButtonIPConfig, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SendButtonIPConfig, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SendButtonIPConfig, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_SendButtonIPConfig, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_SendButtonIPConfig, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_SendButtonIPConfig, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_SendButtonIPConfig, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SendButtonIPConfigLabel = lv_label_create(ui_SendButtonIPConfig);
    lv_obj_set_width(ui_SendButtonIPConfigLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SendButtonIPConfigLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SendButtonIPConfigLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SendButtonIPConfigLabel, "Send");
    lv_obj_set_style_text_color(ui_SendButtonIPConfigLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SendButtonIPConfigLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SendButtonIPConfigLabel, &ui_font_OSF_REG_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_IPDigit1 = lv_roller_create(ui_IPConfigScreen);
    lv_roller_set_options(ui_IPDigit1, "-\n0\n1\n2\n3\n4\n5\n6\n7\n8\n9", LV_ROLLER_MODE_INFINITE);
    lv_obj_set_height(ui_IPDigit1, 100);
    lv_obj_set_width(ui_IPDigit1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_IPDigit1, -192);
    lv_obj_set_y(ui_IPDigit1, -20);
    lv_obj_set_align(ui_IPDigit1, LV_ALIGN_CENTER);
    lv_obj_set_style_text_font(ui_IPDigit1, &ui_font_OSF_REG_22, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_IPDigit1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_IPDigit1, lv_color_hex(0x131313), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_IPDigit1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_IPDigit1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_IPDigit1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_IPDigit1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_IPDigit1, 0, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_IPDigit1, lv_color_hex(0x131313), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_IPDigit1, 125, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_IPDigit1, lv_color_hex(0xD5D6D8), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_IPDigit1, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_IPDigit1, 1, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_IPDisplay = lv_label_create(ui_IPConfigScreen);
    lv_obj_set_width(ui_IPDisplay, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_IPDisplay, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_IPDisplay, -96);
    lv_obj_set_y(ui_IPDisplay, -105);
    lv_obj_set_align(ui_IPDisplay, LV_ALIGN_CENTER);
    lv_label_set_text(ui_IPDisplay, "192.168.10.#00ff00 62#");
    lv_label_set_recolor(ui_IPDisplay, "true");
    lv_obj_set_style_text_color(ui_IPDisplay, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_IPDisplay, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_IPDisplay, &ui_font_OSF_REG_42, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_IPConfigPrevFieldButton = lv_btn_create(ui_IPConfigScreen);
    lv_obj_set_width(ui_IPConfigPrevFieldButton, 56);
    lv_obj_set_height(ui_IPConfigPrevFieldButton, 50);
    lv_obj_set_x(ui_IPConfigPrevFieldButton, -290);
    lv_obj_set_y(ui_IPConfigPrevFieldButton, -20);
    lv_obj_set_align(ui_IPConfigPrevFieldButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_IPConfigPrevFieldButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_IPConfigPrevFieldButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_IPConfigPrevFieldButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_IPConfigPrevFieldButton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_IPConfigPrevFieldButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_IPConfigPrevFieldButton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_IPConfigPrevFieldButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_IPConfigPrevFieldButton, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_IPConfigPrevFieldButton, lv_color_hex(0xD5D6D8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_IPConfigPrevFieldButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_IPConfigPrevFieldButtonLabel = lv_label_create(ui_IPConfigPrevFieldButton);
    lv_obj_set_width(ui_IPConfigPrevFieldButtonLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_IPConfigPrevFieldButtonLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_IPConfigPrevFieldButtonLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_IPConfigPrevFieldButtonLabel, "<");
    lv_obj_set_style_text_font(ui_IPConfigPrevFieldButtonLabel, &lv_font_montserrat_42, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_IPConfigNextFieldButton = lv_btn_create(ui_IPConfigScreen);
    lv_obj_set_width(ui_IPConfigNextFieldButton, 56);
    lv_obj_set_height(ui_IPConfigNextFieldButton, 50);
    lv_obj_set_x(ui_IPConfigNextFieldButton, 98);
    lv_obj_set_y(ui_IPConfigNextFieldButton, -20);
    lv_obj_set_align(ui_IPConfigNextFieldButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_IPConfigNextFieldButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_IPConfigNextFieldButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_IPConfigNextFieldButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_IPConfigNextFieldButton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_IPConfigNextFieldButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_IPConfigNextFieldButton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_IPConfigNextFieldButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_IPConfigNextFieldButton, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_IPConfigNextFieldButton, lv_color_hex(0xD5D6D8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_IPConfigNextFieldButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_IPConfigNextFieldButtonLabel = lv_label_create(ui_IPConfigNextFieldButton);
    lv_obj_set_width(ui_IPConfigNextFieldButtonLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_IPConfigNextFieldButtonLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_IPConfigNextFieldButtonLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_IPConfigNextFieldButtonLabel, ">");
    lv_obj_set_style_text_font(ui_IPConfigNextFieldButtonLabel, &lv_font_montserrat_42, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_IPDigit2 = lv_roller_create(ui_IPConfigScreen);
    lv_roller_set_options(ui_IPDigit2, "-\n0\n1\n2\n3\n4\n5\n6\n7\n8\n9", LV_ROLLER_MODE_INFINITE);
    lv_obj_set_height(ui_IPDigit2, 100);
    lv_obj_set_width(ui_IPDigit2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_IPDigit2, -96);
    lv_obj_set_y(ui_IPDigit2, -20);
    lv_obj_set_align(ui_IPDigit2, LV_ALIGN_CENTER);
    lv_obj_set_style_text_font(ui_IPDigit2, &ui_font_OSF_REG_22, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_IPDigit2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_IPDigit2, lv_color_hex(0x131313), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_IPDigit2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_IPDigit2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_IPDigit2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_IPDigit2, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_IPDigit2, 0, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_IPDigit2, lv_color_hex(0x131313), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_IPDigit2, 125, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_IPDigit2, lv_color_hex(0xD5D6D8), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_IPDigit2, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_IPDigit2, 1, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_IPDigit3 = lv_roller_create(ui_IPConfigScreen);
    lv_roller_set_options(ui_IPDigit3, "-\n0\n1\n2\n3\n4\n5\n6\n7\n8\n9", LV_ROLLER_MODE_INFINITE);
    lv_obj_set_height(ui_IPDigit3, 100);
    lv_obj_set_width(ui_IPDigit3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_IPDigit3, 0);
    lv_obj_set_y(ui_IPDigit3, -20);
    lv_obj_set_align(ui_IPDigit3, LV_ALIGN_CENTER);
    lv_obj_set_style_text_font(ui_IPDigit3, &ui_font_OSF_REG_22, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_IPDigit3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_IPDigit3, lv_color_hex(0x131313), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_IPDigit3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_IPDigit3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_IPDigit3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_IPDigit3, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_IPDigit3, lv_color_hex(0xFFFFFF), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_IPDigit3, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_IPDigit3, &ui_font_OSF_REG_22, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_IPDigit3, 0, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_IPDigit3, lv_color_hex(0x131313), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_IPDigit3, 125, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_IPDigit3, lv_color_hex(0xD5D6D8), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_IPDigit3, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_IPDigit3, 1, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_GV6k_Logo_Home3 = lv_img_create(ui_IPConfigScreen);
    lv_img_set_src(ui_GV6k_Logo_Home3, &ui_img_gv6k_png);
    lv_obj_set_width(ui_GV6k_Logo_Home3, LV_SIZE_CONTENT);   /// 529
    lv_obj_set_height(ui_GV6k_Logo_Home3, LV_SIZE_CONTENT);    /// 501
    lv_obj_set_x(ui_GV6k_Logo_Home3, -353);
    lv_obj_set_y(ui_GV6k_Logo_Home3, -185);
    lv_obj_set_align(ui_GV6k_Logo_Home3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_GV6k_Logo_Home3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_GV6k_Logo_Home3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_GV6k_Logo_Home3, 350);

    ui_GEMINI_LABEL_HOME3 = lv_label_create(ui_IPConfigScreen);
    lv_obj_set_width(ui_GEMINI_LABEL_HOME3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_GEMINI_LABEL_HOME3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_GEMINI_LABEL_HOME3, 86);
    lv_obj_set_y(ui_GEMINI_LABEL_HOME3, 39);
    lv_label_set_text(ui_GEMINI_LABEL_HOME3, "EMINI");
    lv_obj_set_style_text_color(ui_GEMINI_LABEL_HOME3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_GEMINI_LABEL_HOME3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_GEMINI_LABEL_HOME3, &ui_font_OSF_REG_42, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_IPConfigScreen_screen_destroy(void)
{
    if(ui_IPConfigScreen) lv_obj_del(ui_IPConfigScreen);

    // NULL screen variables
    ui_IPConfigScreen = NULL;
    ui_DriveNameIPConfig = NULL;
    ui_StatusLabelIPConfig = NULL;
    ui_HomeButtonIPConfig = NULL;
    ui_HomeButtonIPConfigLabel = NULL;
    ui_ConsoleReadIPConfig = NULL;
    ui_SpinnerIPConfig = NULL;
    ui_SendButtonIPConfig = NULL;
    ui_SendButtonIPConfigLabel = NULL;
    ui_IPDigit1 = NULL;
    ui_IPDisplay = NULL;
    ui_IPConfigPrevFieldButton = NULL;
    ui_IPConfigPrevFieldButtonLabel = NULL;
    ui_IPConfigNextFieldButton = NULL;
    ui_IPConfigNextFieldButtonLabel = NULL;
    ui_IPDigit2 = NULL;
    ui_IPDigit3 = NULL;
    ui_GV6k_Logo_Home3 = NULL;
    ui_GEMINI_LABEL_HOME3 = NULL;

}
