// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project_NO_BG

#include "ui.h"

lv_obj_t * ui_StartupScreen = NULL;
lv_obj_t * ui_LoadingScreenText = NULL;
lv_obj_t * ui_Image1 = NULL;
lv_obj_t * ui_LoadingScreenSpinner = NULL;
// event funtions

// build funtions

void ui_StartupScreen_screen_init(void)
{
    ui_StartupScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_StartupScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_StartupScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_StartupScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LoadingScreenText = lv_label_create(ui_StartupScreen);
    lv_obj_set_width(ui_LoadingScreenText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LoadingScreenText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LoadingScreenText, 0);
    lv_obj_set_y(ui_LoadingScreenText, 178);
    lv_obj_set_align(ui_LoadingScreenText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LoadingScreenText, "Establishing Serial Connection...");
    lv_obj_set_style_text_color(ui_LoadingScreenText, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LoadingScreenText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LoadingScreenText, &ui_font_OSF_REG_42, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image1 = lv_img_create(ui_StartupScreen);
    lv_img_set_src(ui_Image1, &ui_img_1999303404);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 200
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 249
    lv_obj_set_x(ui_Image1, 0);
    lv_obj_set_y(ui_Image1, -31);
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image1, 350);

    ui_LoadingScreenSpinner = lv_spinner_create(ui_StartupScreen, 1000, 90);
    lv_obj_set_width(ui_LoadingScreenSpinner, 232);
    lv_obj_set_height(ui_LoadingScreenSpinner, 231);
    lv_obj_set_align(ui_LoadingScreenSpinner, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_LoadingScreenSpinner, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_style_arc_color(ui_LoadingScreenSpinner, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_LoadingScreenSpinner, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_LoadingScreenSpinner, 25, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_width(ui_LoadingScreenSpinner, 25, LV_PART_INDICATOR | LV_STATE_DEFAULT);

}

void ui_StartupScreen_screen_destroy(void)
{
    if(ui_StartupScreen) lv_obj_del(ui_StartupScreen);

    // NULL screen variables
    ui_StartupScreen = NULL;
    ui_LoadingScreenText = NULL;
    ui_Image1 = NULL;
    ui_LoadingScreenSpinner = NULL;

}
