// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project_NO_BG

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////
lv_anim_t * Loading_Animation(lv_obj_t * TargetObject, int delay);

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////
lv_anim_t * Loading_Animation(lv_obj_t * TargetObject, int delay)
{
    lv_anim_t * out_anim;
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 5000);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_image_angle);
    lv_anim_set_values(&PropertyAnimation_0, 0, 3600);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_ease_in_out);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, LV_ANIM_REPEAT_INFINITE);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, false);
    lv_anim_set_get_value_cb(&PropertyAnimation_0, &_ui_anim_callback_get_image_angle);
    out_anim = lv_anim_start(&PropertyAnimation_0);
    ui_anim_user_data_t * PropertyAnimation_1_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_1_user_data->target = TargetObject;
    PropertyAnimation_1_user_data->val = -1;
    lv_anim_t PropertyAnimation_1;
    lv_anim_init(&PropertyAnimation_1);
    lv_anim_set_time(&PropertyAnimation_1, 1250);
    lv_anim_set_user_data(&PropertyAnimation_1, PropertyAnimation_1_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_1, _ui_anim_callback_set_x);
    lv_anim_set_values(&PropertyAnimation_1, 0, 20);
    lv_anim_set_path_cb(&PropertyAnimation_1, lv_anim_path_ease_in);
    lv_anim_set_delay(&PropertyAnimation_1, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_1, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_1, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_1, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_1, LV_ANIM_REPEAT_INFINITE);
    lv_anim_set_repeat_delay(&PropertyAnimation_1, 3750);
    lv_anim_set_early_apply(&PropertyAnimation_1, false);
    lv_anim_set_get_value_cb(&PropertyAnimation_1, &_ui_anim_callback_get_x);
    out_anim = lv_anim_start(&PropertyAnimation_1);
    ui_anim_user_data_t * PropertyAnimation_2_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_2_user_data->target = TargetObject;
    PropertyAnimation_2_user_data->val = -1;
    lv_anim_t PropertyAnimation_2;
    lv_anim_init(&PropertyAnimation_2);
    lv_anim_set_time(&PropertyAnimation_2, 1250);
    lv_anim_set_user_data(&PropertyAnimation_2, PropertyAnimation_2_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_2, _ui_anim_callback_set_x);
    lv_anim_set_values(&PropertyAnimation_2, 0, -20);
    lv_anim_set_path_cb(&PropertyAnimation_2, lv_anim_path_linear);
    lv_anim_set_delay(&PropertyAnimation_2, delay + 1250);
    lv_anim_set_deleted_cb(&PropertyAnimation_2, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_2, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_2, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_2, LV_ANIM_REPEAT_INFINITE);
    lv_anim_set_repeat_delay(&PropertyAnimation_2, 3750);
    lv_anim_set_early_apply(&PropertyAnimation_2, false);
    lv_anim_set_get_value_cb(&PropertyAnimation_2, &_ui_anim_callback_get_x);
    out_anim = lv_anim_start(&PropertyAnimation_2);
    ui_anim_user_data_t * PropertyAnimation_3_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_3_user_data->target = TargetObject;
    PropertyAnimation_3_user_data->val = -1;
    lv_anim_t PropertyAnimation_3;
    lv_anim_init(&PropertyAnimation_3);
    lv_anim_set_time(&PropertyAnimation_3, 1250);
    lv_anim_set_user_data(&PropertyAnimation_3, PropertyAnimation_3_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_3, _ui_anim_callback_set_x);
    lv_anim_set_values(&PropertyAnimation_3, 0, -20);
    lv_anim_set_path_cb(&PropertyAnimation_3, lv_anim_path_linear);
    lv_anim_set_delay(&PropertyAnimation_3, delay + 2500);
    lv_anim_set_deleted_cb(&PropertyAnimation_3, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_3, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_3, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_3, LV_ANIM_REPEAT_INFINITE);
    lv_anim_set_repeat_delay(&PropertyAnimation_3, 3750);
    lv_anim_set_early_apply(&PropertyAnimation_3, false);
    lv_anim_set_get_value_cb(&PropertyAnimation_3, &_ui_anim_callback_get_x);
    out_anim = lv_anim_start(&PropertyAnimation_3);
    ui_anim_user_data_t * PropertyAnimation_4_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_4_user_data->target = TargetObject;
    PropertyAnimation_4_user_data->val = -1;
    lv_anim_t PropertyAnimation_4;
    lv_anim_init(&PropertyAnimation_4);
    lv_anim_set_time(&PropertyAnimation_4, 1250);
    lv_anim_set_user_data(&PropertyAnimation_4, PropertyAnimation_4_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_4, _ui_anim_callback_set_x);
    lv_anim_set_values(&PropertyAnimation_4, 0, 20);
    lv_anim_set_path_cb(&PropertyAnimation_4, lv_anim_path_ease_out);
    lv_anim_set_delay(&PropertyAnimation_4, delay + 3750);
    lv_anim_set_deleted_cb(&PropertyAnimation_4, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_4, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_4, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_4, LV_ANIM_REPEAT_INFINITE);
    lv_anim_set_repeat_delay(&PropertyAnimation_4, 3750);
    lv_anim_set_early_apply(&PropertyAnimation_4, false);
    lv_anim_set_get_value_cb(&PropertyAnimation_4, &_ui_anim_callback_get_x);
    out_anim = lv_anim_start(&PropertyAnimation_4);
    ui_anim_user_data_t * PropertyAnimation_5_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_5_user_data->target = TargetObject;
    PropertyAnimation_5_user_data->val = -1;
    lv_anim_t PropertyAnimation_5;
    lv_anim_init(&PropertyAnimation_5);
    lv_anim_set_time(&PropertyAnimation_5, 1250);
    lv_anim_set_user_data(&PropertyAnimation_5, PropertyAnimation_5_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_5, _ui_anim_callback_set_y);
    lv_anim_set_values(&PropertyAnimation_5, 0, 25);
    lv_anim_set_path_cb(&PropertyAnimation_5, lv_anim_path_ease_in);
    lv_anim_set_delay(&PropertyAnimation_5, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_5, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_5, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_5, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_5, LV_ANIM_REPEAT_INFINITE);
    lv_anim_set_repeat_delay(&PropertyAnimation_5, 3750);
    lv_anim_set_early_apply(&PropertyAnimation_5, false);
    lv_anim_set_get_value_cb(&PropertyAnimation_5, &_ui_anim_callback_get_y);
    out_anim = lv_anim_start(&PropertyAnimation_5);
    ui_anim_user_data_t * PropertyAnimation_6_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_6_user_data->target = TargetObject;
    PropertyAnimation_6_user_data->val = -1;
    lv_anim_t PropertyAnimation_6;
    lv_anim_init(&PropertyAnimation_6);
    lv_anim_set_time(&PropertyAnimation_6, 1250);
    lv_anim_set_user_data(&PropertyAnimation_6, PropertyAnimation_6_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_6, _ui_anim_callback_set_y);
    lv_anim_set_values(&PropertyAnimation_6, 0, -25);
    lv_anim_set_path_cb(&PropertyAnimation_6, lv_anim_path_linear);
    lv_anim_set_delay(&PropertyAnimation_6, delay + 1250);
    lv_anim_set_deleted_cb(&PropertyAnimation_6, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_6, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_6, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_6, LV_ANIM_REPEAT_INFINITE);
    lv_anim_set_repeat_delay(&PropertyAnimation_6, 3750);
    lv_anim_set_early_apply(&PropertyAnimation_6, false);
    lv_anim_set_get_value_cb(&PropertyAnimation_6, &_ui_anim_callback_get_y);
    out_anim = lv_anim_start(&PropertyAnimation_6);
    ui_anim_user_data_t * PropertyAnimation_7_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_7_user_data->target = TargetObject;
    PropertyAnimation_7_user_data->val = -1;
    lv_anim_t PropertyAnimation_7;
    lv_anim_init(&PropertyAnimation_7);
    lv_anim_set_time(&PropertyAnimation_7, 1250);
    lv_anim_set_user_data(&PropertyAnimation_7, PropertyAnimation_7_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_7, _ui_anim_callback_set_y);
    lv_anim_set_values(&PropertyAnimation_7, 0, 25);
    lv_anim_set_path_cb(&PropertyAnimation_7, lv_anim_path_linear);
    lv_anim_set_delay(&PropertyAnimation_7, delay + 2500);
    lv_anim_set_deleted_cb(&PropertyAnimation_7, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_7, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_7, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_7, LV_ANIM_REPEAT_INFINITE);
    lv_anim_set_repeat_delay(&PropertyAnimation_7, 3750);
    lv_anim_set_early_apply(&PropertyAnimation_7, false);
    lv_anim_set_get_value_cb(&PropertyAnimation_7, &_ui_anim_callback_get_y);
    out_anim = lv_anim_start(&PropertyAnimation_7);
    ui_anim_user_data_t * PropertyAnimation_8_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_8_user_data->target = TargetObject;
    PropertyAnimation_8_user_data->val = -1;
    lv_anim_t PropertyAnimation_8;
    lv_anim_init(&PropertyAnimation_8);
    lv_anim_set_time(&PropertyAnimation_8, 1250);
    lv_anim_set_user_data(&PropertyAnimation_8, PropertyAnimation_8_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_8, _ui_anim_callback_set_y);
    lv_anim_set_values(&PropertyAnimation_8, 0, -25);
    lv_anim_set_path_cb(&PropertyAnimation_8, lv_anim_path_ease_out);
    lv_anim_set_delay(&PropertyAnimation_8, delay + 3750);
    lv_anim_set_deleted_cb(&PropertyAnimation_8, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_8, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_8, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_8, LV_ANIM_REPEAT_INFINITE);
    lv_anim_set_repeat_delay(&PropertyAnimation_8, 3750);
    lv_anim_set_early_apply(&PropertyAnimation_8, false);
    lv_anim_set_get_value_cb(&PropertyAnimation_8, &_ui_anim_callback_get_y);
    out_anim = lv_anim_start(&PropertyAnimation_8);

    return out_anim;
}

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_IPConfigScreen_screen_init();
    ui_MotorConfigScreen_screen_init();
    ui_HomeScreen_screen_init();
    ui_SleepScreen_screen_init();
    ui_DriveStatusScreen_screen_init();
    ui_StartupScreen_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_IPConfigScreen);
}

void ui_destroy(void)
{
    ui_IPConfigScreen_screen_destroy();
    ui_MotorConfigScreen_screen_destroy();
    ui_HomeScreen_screen_destroy();
    ui_SleepScreen_screen_destroy();
    ui_DriveStatusScreen_screen_destroy();
    ui_StartupScreen_screen_destroy();
}
