// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project_NO_BG

#ifndef _SQUARELINE_PROJECT_NO_BG_UI_H
#define _SQUARELINE_PROJECT_NO_BG_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

///////////////////// SCREENS ////////////////////

#include "ui_IPConfigScreen.h"
#include "ui_MotorConfigScreen.h"
#include "ui_HomeScreen.h"
#include "ui_SleepScreen.h"
#include "ui_DriveStatusScreen.h"
#include "ui_StartupScreen.h"

///////////////////// VARIABLES ////////////////////

extern lv_anim_t * Loading_Animation(lv_obj_t * TargetObject, int delay);

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_gv6k_png);    // assets/GV6k.png
LV_IMG_DECLARE(ui_img_1999303404);    // assets/output-onlinepngtools.png

// FONTS
LV_FONT_DECLARE(ui_font_OSF24);
LV_FONT_DECLARE(ui_font_OSF42);
LV_FONT_DECLARE(ui_font_OSF_72);
LV_FONT_DECLARE(ui_font_OSF_REG_12);
LV_FONT_DECLARE(ui_font_OSF_REG_22);
LV_FONT_DECLARE(ui_font_OSF_REG_30);
LV_FONT_DECLARE(ui_font_OSF_REG_42);
LV_FONT_DECLARE(ui_font_OSF_REG_16);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
