// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project_NO_BG

#ifndef UI_HOMESCREEN_H
#define UI_HOMESCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_HomeScreen
extern void ui_HomeScreen_screen_init(void);
extern void ui_HomeScreen_screen_destroy(void);
extern lv_obj_t * ui_HomeScreen;
extern lv_obj_t * ui_StatusLabelHome;
extern lv_obj_t * ui_DriveName;
extern lv_obj_t * ui_IPConfigButtonHome;
extern lv_obj_t * ui_IPConfigButtonHomeLabel;
extern lv_obj_t * ui_IPConfigButtonTitle;
extern lv_obj_t * ui_MotorConfigButtonHome;
extern lv_obj_t * ui_MotorConfigButtonHomeLabel;
extern lv_obj_t * ui_MotorConfigButtonTitle;
extern lv_obj_t * ui_DriveStatusButtonHome;
extern lv_obj_t * ui_DriveStatusButtonHomeLabel;
extern lv_obj_t * ui_DriveStatusButtonTitle;
extern lv_obj_t * ui_GV6k_Logo_Home;
extern lv_obj_t * ui_GEMINI_LABEL_HOME;
extern lv_obj_t * ui_OSF_Logo_Home;
extern lv_obj_t * ui_OSF_LABEL;
extern lv_obj_t * ui_AUTOMATION_LABEL;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

