// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project_NO_BG

#ifndef UI_MOTORCONFIGSCREEN_H
#define UI_MOTORCONFIGSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_MotorConfigScreen
extern void ui_MotorConfigScreen_screen_init(void);
extern void ui_MotorConfigScreen_screen_destroy(void);
extern lv_obj_t * ui_MotorConfigScreen;
extern lv_obj_t * ui_HomeButtonMotorConfig;
extern lv_obj_t * ui_HomeButtonMotorConfigLabel;
extern lv_obj_t * ui_MotorConfigSelect;
extern lv_obj_t * ui_ConsoleReadMotorConfig;
extern lv_obj_t * ui_SendButtonMotorConfig;
extern lv_obj_t * ui_SendButtonMotorConfigLabel;
extern lv_obj_t * ui_SpinnerMotorConfig;
extern lv_obj_t * ui_DriveNameMotorConfig;
extern lv_obj_t * ui_StatusLabelMotorConfig;
extern lv_obj_t * ui_GV6k_Logo_Home4;
extern lv_obj_t * ui_GEMINI_LABEL_HOME4;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

