// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project_NO_BG

#include "ui.h"

lv_obj_t * ui_MotorConfigScreen = NULL;
lv_obj_t * ui_HomeButtonMotorConfig = NULL;
lv_obj_t * ui_HomeButtonMotorConfigLabel = NULL;
lv_obj_t * ui_MotorConfigSelect = NULL;
lv_obj_t * ui_ConsoleReadMotorConfig = NULL;
lv_obj_t * ui_SendButtonMotorConfig = NULL;
lv_obj_t * ui_SendButtonMotorConfigLabel = NULL;
lv_obj_t * ui_SpinnerMotorConfig = NULL;
lv_obj_t * ui_DriveNameMotorConfig = NULL;
lv_obj_t * ui_StatusLabelMotorConfig = NULL;
lv_obj_t * ui_GV6k_Logo_Home4 = NULL;
lv_obj_t * ui_GEMINI_LABEL_HOME4 = NULL;
// event funtions

// build funtions

void ui_MotorConfigScreen_screen_init(void)
{
    ui_MotorConfigScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_MotorConfigScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_MotorConfigScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MotorConfigScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HomeButtonMotorConfig = lv_btn_create(ui_MotorConfigScreen);
    lv_obj_set_width(ui_HomeButtonMotorConfig, 200);
    lv_obj_set_height(ui_HomeButtonMotorConfig, 66);
    lv_obj_set_x(ui_HomeButtonMotorConfig, 250);
    lv_obj_set_y(ui_HomeButtonMotorConfig, -145);
    lv_obj_set_align(ui_HomeButtonMotorConfig, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_HomeButtonMotorConfig, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_HomeButtonMotorConfig, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_HomeButtonMotorConfig, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_HomeButtonMotorConfig, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HomeButtonMotorConfig, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_HomeButtonMotorConfig, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_HomeButtonMotorConfig, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_HomeButtonMotorConfig, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_HomeButtonMotorConfig, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HomeButtonMotorConfigLabel = lv_label_create(ui_HomeButtonMotorConfig);
    lv_obj_set_width(ui_HomeButtonMotorConfigLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HomeButtonMotorConfigLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_HomeButtonMotorConfigLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HomeButtonMotorConfigLabel, "Home");
    lv_obj_set_style_text_color(ui_HomeButtonMotorConfigLabel, lv_color_hex(0xD5D6D8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_HomeButtonMotorConfigLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HomeButtonMotorConfigLabel, &ui_font_OSF_REG_42, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MotorConfigSelect = lv_dropdown_create(ui_MotorConfigScreen);
    lv_dropdown_set_options(ui_MotorConfigSelect,
                            "BE 232 DJ\nBE 233 DJ\nBE 343 JJ\nMPP 100 3D1E\nMPP 155 3D1E\nMPP 142 4B1E");
    lv_obj_set_width(ui_MotorConfigSelect, 274);
    lv_obj_set_height(ui_MotorConfigSelect, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MotorConfigSelect, -211);
    lv_obj_set_y(ui_MotorConfigSelect, -18);
    lv_obj_set_align(ui_MotorConfigSelect, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_MotorConfigSelect, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_color(ui_MotorConfigSelect, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MotorConfigSelect, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MotorConfigSelect, &ui_font_OSF_REG_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_MotorConfigSelect, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_MotorConfigSelect, lv_color_hex(0xFAFAFA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MotorConfigSelect, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_MotorConfigSelect, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_MotorConfigSelect, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_MotorConfigSelect, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_MotorConfigSelect, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_MotorConfigSelect, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_MotorConfigSelect, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_MotorConfigSelect, 20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(ui_MotorConfigSelect, &lv_font_montserrat_30, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_ConsoleReadMotorConfig = lv_textarea_create(ui_MotorConfigScreen);
    lv_obj_set_width(ui_ConsoleReadMotorConfig, 800);
    lv_obj_set_height(ui_ConsoleReadMotorConfig, 167);
    lv_obj_set_align(ui_ConsoleReadMotorConfig, LV_ALIGN_BOTTOM_MID);
    lv_textarea_set_placeholder_text(ui_ConsoleReadMotorConfig, "SAMPLE CONSOLE READOUT");
    lv_obj_clear_flag(ui_ConsoleReadMotorConfig,
                      LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_obj_set_style_text_color(ui_ConsoleReadMotorConfig, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ConsoleReadMotorConfig, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ConsoleReadMotorConfig, &ui_font_OSF_REG_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_ConsoleReadMotorConfig, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ConsoleReadMotorConfig, lv_color_hex(0x131313), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ConsoleReadMotorConfig, 125, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ConsoleReadMotorConfig, lv_color_hex(0xD5D6D8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ConsoleReadMotorConfig, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ConsoleReadMotorConfig, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_ConsoleReadMotorConfig, LV_BORDER_SIDE_TOP, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SendButtonMotorConfig = lv_btn_create(ui_MotorConfigScreen);
    lv_obj_set_width(ui_SendButtonMotorConfig, 373);
    lv_obj_set_height(ui_SendButtonMotorConfig, 75);
    lv_obj_set_x(ui_SendButtonMotorConfig, 186);
    lv_obj_set_y(ui_SendButtonMotorConfig, -18);
    lv_obj_set_align(ui_SendButtonMotorConfig, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SendButtonMotorConfig, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_SendButtonMotorConfig, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_SendButtonMotorConfig, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SendButtonMotorConfig, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SendButtonMotorConfig, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_SendButtonMotorConfig, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_SendButtonMotorConfig, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_SendButtonMotorConfig, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_SendButtonMotorConfig, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SendButtonMotorConfigLabel = lv_label_create(ui_SendButtonMotorConfig);
    lv_obj_set_width(ui_SendButtonMotorConfigLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SendButtonMotorConfigLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SendButtonMotorConfigLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SendButtonMotorConfigLabel, "SEND CONFIGURATION");
    lv_obj_set_style_text_color(ui_SendButtonMotorConfigLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SendButtonMotorConfigLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SendButtonMotorConfigLabel, &ui_font_OSF_REG_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SpinnerMotorConfig = lv_spinner_create(ui_MotorConfigScreen, 1000, 90);
    lv_obj_set_width(ui_SpinnerMotorConfig, 56);
    lv_obj_set_height(ui_SpinnerMotorConfig, 56);
    lv_obj_set_x(ui_SpinnerMotorConfig, -38);
    lv_obj_set_y(ui_SpinnerMotorConfig, -18);
    lv_obj_set_align(ui_SpinnerMotorConfig, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SpinnerMotorConfig, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_SpinnerMotorConfig, LV_OBJ_FLAG_CLICKABLE);      /// Flags

    ui_DriveNameMotorConfig = lv_label_create(ui_MotorConfigScreen);
    lv_obj_set_width(ui_DriveNameMotorConfig, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DriveNameMotorConfig, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DriveNameMotorConfig, 230);
    lv_obj_set_y(ui_DriveNameMotorConfig, 25);
    lv_label_set_text(ui_DriveNameMotorConfig, "U12");
    lv_obj_set_style_text_color(ui_DriveNameMotorConfig, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DriveNameMotorConfig, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_DriveNameMotorConfig, &ui_font_OSF_72, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_StatusLabelMotorConfig = lv_label_create(ui_MotorConfigScreen);
    lv_obj_set_width(ui_StatusLabelMotorConfig, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_StatusLabelMotorConfig, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_StatusLabelMotorConfig, 522);
    lv_obj_set_y(ui_StatusLabelMotorConfig, -204);
    lv_obj_set_align(ui_StatusLabelMotorConfig, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_StatusLabelMotorConfig, "NOT CONNECTED");
    lv_obj_set_style_text_color(ui_StatusLabelMotorConfig, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_StatusLabelMotorConfig, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_StatusLabelMotorConfig, &ui_font_OSF_REG_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_GV6k_Logo_Home4 = lv_img_create(ui_MotorConfigScreen);
    lv_img_set_src(ui_GV6k_Logo_Home4, &ui_img_gv6k_png);
    lv_obj_set_width(ui_GV6k_Logo_Home4, LV_SIZE_CONTENT);   /// 529
    lv_obj_set_height(ui_GV6k_Logo_Home4, LV_SIZE_CONTENT);    /// 501
    lv_obj_set_x(ui_GV6k_Logo_Home4, -353);
    lv_obj_set_y(ui_GV6k_Logo_Home4, -185);
    lv_obj_set_align(ui_GV6k_Logo_Home4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_GV6k_Logo_Home4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_GV6k_Logo_Home4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_GV6k_Logo_Home4, 350);

    ui_GEMINI_LABEL_HOME4 = lv_label_create(ui_MotorConfigScreen);
    lv_obj_set_width(ui_GEMINI_LABEL_HOME4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_GEMINI_LABEL_HOME4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_GEMINI_LABEL_HOME4, 86);
    lv_obj_set_y(ui_GEMINI_LABEL_HOME4, 39);
    lv_label_set_text(ui_GEMINI_LABEL_HOME4, "EMINI");
    lv_obj_set_style_text_color(ui_GEMINI_LABEL_HOME4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_GEMINI_LABEL_HOME4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_GEMINI_LABEL_HOME4, &ui_font_OSF_REG_42, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_MotorConfigScreen_screen_destroy(void)
{
    if(ui_MotorConfigScreen) lv_obj_del(ui_MotorConfigScreen);

    // NULL screen variables
    ui_MotorConfigScreen = NULL;
    ui_HomeButtonMotorConfig = NULL;
    ui_HomeButtonMotorConfigLabel = NULL;
    ui_MotorConfigSelect = NULL;
    ui_ConsoleReadMotorConfig = NULL;
    ui_SendButtonMotorConfig = NULL;
    ui_SendButtonMotorConfigLabel = NULL;
    ui_SpinnerMotorConfig = NULL;
    ui_DriveNameMotorConfig = NULL;
    ui_StatusLabelMotorConfig = NULL;
    ui_GV6k_Logo_Home4 = NULL;
    ui_GEMINI_LABEL_HOME4 = NULL;

}
