// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project_NO_BG

#ifndef UI_STARTUPSCREEN_H
#define UI_STARTUPSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_StartupScreen
extern void ui_StartupScreen_screen_init(void);
extern void ui_StartupScreen_screen_destroy(void);
extern lv_obj_t * ui_StartupScreen;
extern lv_obj_t * ui_LoadingScreenText;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_LoadingScreenSpinner;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

