// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project_NO_BG

#ifndef UI_SLEEPSCREEN_H
#define UI_SLEEPSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_SleepScreen
extern void ui_SleepScreen_screen_init(void);
extern void ui_SleepScreen_screen_destroy(void);
extern lv_obj_t * ui_SleepScreen;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

