// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project_NO_BG

#include "ui.h"

lv_obj_t * ui_SleepScreen = NULL;
// event funtions

// build funtions

void ui_SleepScreen_screen_init(void)
{
    ui_SleepScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_SleepScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SleepScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SleepScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_SleepScreen_screen_destroy(void)
{
    if(ui_SleepScreen) lv_obj_del(ui_SleepScreen);

    // NULL screen variables
    ui_SleepScreen = NULL;

}
